### ISSUE TITLE
Cannot refresh the page

### ISSUE THREAD

**Issue by jramiroz98** [JonasJs/svelte-qrcode#17]
I added a QR code to the page that corresponds to contact, but whenever I hit refresh i get 500 internal error.

In my terminal highlighted in red I get:
Internal server error: Cannot set properties of undefined (setting 'QRious')

Aside from that your project is awesome man! thank you so much

**Comment by Kaikeplatinium** [comment]
i got the same, let me know if you get to fix it

**Comment by jramiroz98** [comment]
My fix was to save the QR code as an image and place it where I needed it to be. Works like a charm. I know it doesn’t fix the reload issue but solves the problem for me.

**Comment by JonasJs** [comment]
🚪✨ Closing this issue – Resolved in the latest version! ✅
