### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'QRious')

### ISSUE THREAD

**Issue by igorhsil** [JonasJs/svelte-qrcode#19]
Trying to add QrCode into my Svelte app

I've put everything like in the example

but got this error:
`[vite] Error when evaluating SSR module /src/components/UserLockers.svelte: failed to import "/node_modules/svelte-qrcode/src/lib/index.svelte"
|- TypeError: Cannot set properties of undefined (setting 'QRious')
`

**Comment by JonasJs** [comment]
Hello, I am developing a new version of the package; I will bring updates soon.
