### ISSUE TITLE
Padding prop behaves strangely 

### ISSUE THREAD

**Issue by codymikol** [JonasJs/svelte-qrcode#2]
On the demo site, try setting the padding to 15 and the QrCode will render with uneven padding

example => https://prop.to/mB2v1tMliJ/1

I'm thinking this might be specific to QRious, but don't have much more time to investigate

**Comment by JonasJs** [comment]
@codymikol I fixed the lib code, and now the qr code centralizes perfectly with the padding

Updated version
https://www.npmjs.com/package/svelte-qrcode
