### ISSUE TITLE
npm ERR! Cannot read properties of null (reading 'matches') Using Sveltekit 2 and svelte 5

### ISSUE THREAD

**Issue by jramiroz98** [JonasJs/svelte-qrcode#20]
I am trying to install this package and get the following errors. I have used this package successfully before.

> npm ERR! Cannot read properties of null (reading 'matches')

also my error window read the following:

`Cannot set properties of undefined (setting 'QRious')`

Currently using "svelte": "^5.0.0-next.1", "@sveltejs/kit": "^2.0.0"
Thanks for your time!

**Comment by JonasJs** [comment]
Hello, I am developing a new version of the package; I will bring updates soon.

**Comment by JonasJs** [comment]
new version available
