### ISSUE TITLE
qrcode not reactively changing

### ISSUE THREAD

**Issue by b3b00** [JonasJs/svelte-qrcode#3]
When changing value of the QrCode component, the qrcode image does not change.
Here is a sample REPL to reproduce :
[qrcode not changing](https://svelte.dev/repl/e50ca90b513d423798d0d4ddfda66a1e?version=3.22.3)

**Comment by JonasJs** [comment]
@b3b00 We fixed this in the most current version
https://www.npmjs.com/package/svelte-qrcode

**Comment by JonasJs** [comment]
@b3b00 In your example it is already working because it gets the most updated version of the package

Example: [qrcode changing](https://svelte.dev/repl/e50ca90b513d423798d0d4ddfda66a1e?version=3.22.3)

**Comment by JonasJs** [comment]
Hi @b3b00, I'm closing this issue
