### ISSUE TITLE
Svelte not recognizing script

### ISSUE THREAD

**Issue by Vanderscycle** [JonasJs/svelte-qrcode#9]
Hi, I have the following error when importing QrCode from "svelte-qr"

I am using vite/svelte and keep on giving me the error that it could not  find a declaration file for module 'svelte-qrcode' even when installed in my package.json

my simple code:
script
```svelte
<style global lang="postcss">
  .qrcode {
    position:relative
    }
  .scale-20 {
      --tw-scale-x: .2;
      --tw-scale-y: .2;
    }
</style>

<script lang="ts">
  import QrCode from "svelte-qrcode"
  export let name: string;
  let  WxH:number = 400
</script>

<template>

  <div class="relative">
    <!-- <div class="square relative"></div> -->
    <QrCode value="https://github.com/JonasJs/svelte-qrcode/blob/master/src/lib/qrcode/index.js" errorCorrection="H" size={WxH} class="relative"/>

  </div>
</template>

```

**Comment by JonasJs** [comment]
@24jr Take a look at this answer, I believe it can help you

sveltejs/kit#928 (comment)

**Comment by JonasJs** [comment]
@Vanderscycle  Take a look at this answer, I believe it can help you

https://github.com/sveltejs/kit/issues/928#issuecomment-817319840

**Comment by Vanderscycle** [comment]
@JonasJs awesome, I'll refer to it.
